### ISSUE TITLE
load checkpoints fail

### ISSUE THREAD

**Issue by Sword-Nomad** [lowrollr/turbozero#23]
I want to restore my checkpoints
```
import orbax.checkpoint as ocp
checkpoint_manager = ocp.CheckpointManager(
    directory=ckpt_dir
    options=ocp.CheckpointManagerOptions(max_to_keep=2)
)
latest_step = checkpoint_manager.latest_step()
trainer.load_train_state_from_checkpoint(config.ckpt_dir + '/' + str(latest_step))
output = trainer.train_loop(
    seed=0,
    num_epochs=1000,
    eval_every=5,
)
```
WARNING:absl:Configured `CheckpointManager` using deprecated legacy API. Please follow the instructions at https://orbax.readthedocs.io/en/latest/api_refactor.html to migrate.
Latest step: 49
/opt/miniconda/envs/turbozero/lib/python3.11/site-packages/orbax/checkpoint/_src/serialization/type_handlers.py:1123: UserWarning: Couldn't find sharding info under RestoreArgs. Populating sharding info from sharding file. Please note restoration time will be slightly increased due to reading from file instead of directly from RestoreArgs. Note also that this option is unsafe when restoring on a different topology than the checkpoint was saved with.

I found that I couldn't restore the checkpoint, it built a new checkpoints instead.  Maybe the API of function save_checkpoint and load_train_state_from_checkpoint should be upgraded.

**Comment by lowrollr** [comment]
resolved in https://github.com/lowrollr/turbozero/pull/22
