### ISSUE TITLE
speed issue

### ISSUE THREAD

**Issue by Nightbringers** [lowrollr/turbozero#7]
hello，mctx-az don't have issue button， so i ask here. 
The speed of alphazero_policy  is much slower than gumbel_muzero_policy in my test, do you know why? And  muzero_policy also much  slower than gumbel_muzero_policy in my test.  what may cause this?

**Comment by lowrollr** [comment]
I am looking into this.

I have enabled issues for mctx-az, you can create this issue there now. Sorry for the confusion.
